### ISSUE TITLE
No Message provided

### ISSUE THREAD

**Issue by mderubertis** [fbsamples/graph-api-webhooks-samples#1]
I get 'No Message provided' when the webhook is called from the Facebook App. (on line 'console.log(req.body);'
[main.txt](https://github.com/fbsamples/graph-api-webhooks-samples/files/57503/main.txt)

.

**Comment by adamgross42** [comment]
Hi @mderubertis - what kinds of Webhooks updates are you expecting to the `/facebook` endpoint?

**Comment by mderubertis** [comment]
@adamgross42 I'm expecting to get data on when a page I'm subscribed to adds a new event or post.

**Comment by adamgross42** [comment]
You're right, @mderubertis !  I do see an issue, and I will fix it shortly.

**Comment by mderubertis** [comment]
Thank you @adamgross42 for your fix! Unable to test now but I will tomorrow.
