### ISSUE TITLE
express deprecated req.param(name)

### ISSUE THREAD

**Issue by sheksushant** [fbsamples/graph-api-webhooks-samples#17]
express deprecated req.param(name): Use req.params, req.body, or req.query instead app.js

how to fix this error?

**Comment by revaxl** [comment]
you can change the app.get part to this:
`app.get('/webhook', function(req, res) {   
  if (
    req.query['hub.mode'] == 'subscribe' &&
    req.query['hub.verify_token'] == token
  ) {
    res.send(req.query['hub.challenge']);
    console.log('ok');
  } else {
    res.sendStatus(400);
  }
});`
don't forget to change the 'webhook'

**Comment by Kilenaitor** [comment]
Updated in latest commit: https://github.com/fbsamples/graph-api-webhooks-samples/commit/109af68de60de271a16076aaff30f6b6584b86a6
