### ISSUE TITLE
How to validate the facebook app

### ISSUE THREAD

**Issue by patrickegp** [fbsamples/graph-api-webhooks-samples#19]
I have done everything but facebook does'nt allow me to publish the app to live cuz they can see where i m requesting my facebook token cuz its a server side integration/

any help?

**Comment by Kilenaitor** [comment]
This appears to be unrelated to this project itself and instead is a general support question. Going to close as off-topic. 

Documentation for App Review is here: https://developers.facebook.com/docs/facebook-login/review/how-to-submit

For additional support, please file a bug at: https://developers.facebook.com/support/bugs/.
