### ISSUE TITLE
Signature check

### ISSUE THREAD

**Issue by Aliance** [fbsamples/graph-api-webhooks-samples#2]
Why there are no `X-Hub-Signature` [check](https://developers.facebook.com/docs/graph-api/webhooks#receiveupdates) in this examples?

**Comment by adamgross42** [comment]
The initial version was just a basic implementation, and checking the `X-Hub-Signature` is not required.  Definitely a good idea to add this in though, let's leave this issue open to remember.  Pull requests are welcome :)

**Comment by Aliance** [comment]
There are 2 examples now: coffee and node, am I right? I can add a PHP Example, may I?

**Comment by adamgross42** [comment]
Correct, those are the two examples right now, aligned with hosting services for executing them.  You're welcome to add a PHP example as well.

**Comment by adamgross42** [comment]
Another thought about the `X-Hub-Signature` value - it would require the app secret be available to the server, which would be an additional step beyond basic configuration.

**Comment by adamgross42** [comment]
Closed by #4
