### ISSUE TITLE
Empty entry on Parse

### ISSUE THREAD

**Issue by GPack1** [fbsamples/graph-api-webhooks-samples#6]
When a new post is published by Page I get like an empty array from Page-Feed webhook subscribed.
On console I see:

> Facebook request body:
> {"entry":[{}],"object":"page"}
 
Callback endpoint is on Parse. Im using the example here.

**Comment by adamgross42** [comment]
Hey @GPack1 - this appears to be empty data received by your process, I don't think this is a code issue, but potentially a configuration issue.  If you think you're not receiving data you're supposed to, the best course of action would be to file a bug here: https://developers.facebook.com/bugs/
