### ISSUE TITLE
Warning - request header X-Hub-Signature not present or invalid

### ISSUE THREAD

**Issue by Lorentzen1337** [fbsamples/graph-api-webhooks-samples#7]
Using the heroku example results in the issue even though req.headers reveal the following:
'x-hub-signature': 'sha1=XXXXXXXXXXXXXXXXXXXXXXXXXX'

I might however have found the issue:
```
app.use(bodyParser.json());
app.use(xhub({ algorithm: 'sha1', secret: process.env.APP_SECRET }));
```

Should be like this according to Express X-Hub README:
```
app.use(xhub({ algorithm: 'sha1', secret: process.env.APP_SECRET }));
app.use(bodyParser.json());
```

Because the [README](https://github.com/alexcurtis/express-x-hub/blob/master/README.md) specifies that it should be added before bodyParser:

> Then add the middleware to Express.js. It needs to be one of the first and before bodyParser().

**Comment by adamgross42** [comment]
@Lorentzen1337 thanks for pointing this out!  This has been fixed by #8.
