### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by enod** [fbsamples/graph-api-webhooks-samples#9]
Followed the guide and got following error from facebook webhook validation: The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 400; HTTP Message = Bad Request
I've deployed using heroku. Any idea?

**Comment by adamgross42** [comment]
Hey @enod, thanks for reaching out.  I'd suggest checking the logs on your Heroku instance for more details.  I'm not aware of other instances of this happening.
